### ISSUE TITLE
Mark DLL Loader file as "Engine Injector" on Nexus

### ISSUE THREAD

**Issue by MaverickMartyn** [Sumwunn/AchievementsModsEnabler#7]
Would you consider marking the optional "DLL Loader" file as an "Engine Injector"?
That way, Vortex will know to install it in the root game directory, instead of the /Data directory, and you can enable Mod Manager downloads.
It would streamline the install process and make easier for newbies.
I'm not sure exactly how to do this, but I imagine you could look at F4SE or SKSE, since their mod files do it.

**Comment by Sumwunn** [comment]
Thanks. I'll have a look around.
